api/app/Database/Doctrine/Mappings/AlbumMapping.php
api/app/Database/Doctrine/Mappings/ReciterMapping.php
api/app/Database/Doctrine/Mappings/TrackMapping.php
api/app/Entities/Album.php
api/app/Entities/Reciter.php
api/app/Entities/Track.php
api/app/Http/Transformers/ReciterTransformer.php
api/app/Http/Transformers/TrackTransformer.php
api/app/Queries/ReciterQuery.php
api/app/Queries/TrackQuery.php
api/app/Repositories/Doctrine/DoctrineReciterRepository.php
api/config/doctrine.php
api/database/migrations/doctrine/Version20200211130444.php
api/database/migrations/doctrine/Version20200211131945.php
api/database/seeds/TestDataSeeder.php

Also fixed the `year` field in Album to be string to support string like `2010-11`.

Basic Slugging Support

---

.github/workflows/vue.yml

Add Vue Github workflow

---

api/app/Http/Transformers/AlbumTransformer.php

Return artwork field for album in API.

---

web/src/components/Album.vue
web/src/store/modules/albums.js

Removed Album and Tracks Pagination on albums card

---

web/src/components/Album.vue

Fixed Album title on the album component

---

web/src/store/modules/tracks.js
web/src/views/public/tracks/Show.vue

Made tracks page use one call instead of three

---

.gitignore
api/app/Console/Commands/ImportDataCommand.php
api/app/Console/Helpers/TrackNameIdentifier.php
api/app/Database/Doctrine/EntityManager.php
api/app/Database/Doctrine/Mappings/AlbumMapping.php
api/app/Database/Doctrine/Mappings/TrackMapping.php
api/app/Entities/Reciter.php
api/app/Queries/ReciterQuery.php
api/app/Queries/TrackQuery.php
api/database/migrations/doctrine/Version20200216151105.php
api/tests/Unit/Console/Helpers/TrackNameIdentifierTest.php

First pass at the Data Import script.
More details coming soon.
Closes #6

Data Import Script

---

.github/workflows/vue.yml
web/.eslintrc.js
web/src/store/modules/albums.js
web/src/store/modules/reciters.js
web/src/views/public/reciters/Index.vue
web/src/views/public/reciters/Show.vue
web/vue.config.js

Added pagination to reciters page

---

web/src/views/public/tracks/Show.vue

Fix track lyrics display.

---

api/app/Http/Controllers/Api/AlbumsController.php
api/app/Http/Controllers/Api/RecitersController.php
api/app/Queries/AlbumQuery.php
api/app/Queries/ReciterQuery.php

Add default sorting to the API

---

api/app/Database/Doctrine/Mappings/TrackMapping.php
api/app/Entities/Track.php
api/app/Http/Controllers/Api/PopularEntitiesController.php
api/app/Queries/Query.php
api/app/Queries/TrackQuery.php
api/composer.json
api/composer.lock
api/config/doctrine.php
api/database/migrations/doctrine/Version20200217171534.php

Closes #42
This is still a crappy "for now" implementation. We'll eventually do a proper Popular Entities API.

Fix popular entities API

---

web/src/views/Home.vue
web/src/views/public/reciters/Index.vue
web/src/views/public/reciters/Show.vue
web/src/views/public/tracks/Show.vue

fixing-loading-states

---

web/src/layouts/Public.vue

Remove login button.

---

api/app/Entities/Track.php
api/app/Http/Transformers/ReciterTransformer.php
api/app/Http/Transformers/TrackTransformer.php
api/app/Providers/RouteServiceProvider.php
api/app/Queries/Query.php

Closes #45 
This PR adds metadata via the API that you can include via the `include` query param. 
```bash
> curl https://api.nawhas.test/v1/reciters/nadeem-sarwar/albums?include=tracks.related&per_page=1
```
```jsonc
{
"data": [
{
"id": "9ac711c0-5404-11ea-b6f1-6eb465563d0f",
"reciterId": "36687336-5404-11ea-8527-6eb465563d0f",
"title": "Badshah Hussain A.S",
"year": "2016-17",
"artwork": null,
"createdAt": "2020-02-20T17:15:34+00:00",
"updatedAt": "2020-02-20T17:15:34+00:00",
"tracks": {
"data": [
{
"id": "9ad33c3e-5404-11ea-ab49-6eb465563d0f",
"reciterId": "36687336-5404-11ea-8527-6eb465563d0f",
"albumId": "9ac711c0-5404-11ea-b6f1-6eb465563d0f",
"title": "Hallo Momino",
"slug": "hallo-momino",
"year": "2016-17",
"createdAt": "2020-02-20T17:15:34+00:00",
"updatedAt": …
```

Track and Reciter Metadata via APIs

---

web/src/components/MoreTracksSkeleton.vue
web/src/views/public/reciters/Show.vue
web/src/views/public/tracks/Show.vue

Track Page Redesign

---

web/src/components/ReciterCard.vue

Add white border around reciter card avatar.

---

api/app/Http/Controllers/Api/PopularEntitiesController.php
api/app/Queries/ReciterQuery.php

Until we figure out a nice way to track popularity...

Hardcode popular reciters for now.

---

web/src/components/TrackCard.vue
web/src/views/public/Home.vue
web/src/views/public/reciters/Show.vue

Make popular tracks colored.

---

api/app/Http/Controllers/Api/AlbumsController.php
api/app/Http/Controllers/Api/RecitersController.php
api/app/Http/Controllers/Api/TracksController.php
api/routes/api.php

Co-Authored-By: Asif Ali <shea786@live.co.uk>
Add APIs to allow creating tracks and albums.

Create Entity APIs

---

api/app/Database/Doctrine/EntityManager.php
api/app/Database/Doctrine/Mappings/TrackMapping.php
api/app/Http/Controllers/Api/TracksController.php
api/app/Repositories/Doctrine/DoctrineTrackRepository.php
api/app/Repositories/TrackRepository.php
api/routes/api.php

https://staging-nawhas-pr-78.onrender.com/reciters/mir-hasan-mir
Mir Hassan Mir has an improperly merged album. To fix this I need to expose the ability to delete tracks.

Add API to delete tracks.

---

web/src/store/modules/player.ts
web/src/views/public/tracks/Show.vue

Deploy - 2020-03-09

---

web/package.json
web/src/components/audio-player/AudioPlayer.vue
web/src/components/audio-player/QueueList.vue
web/src/store/modules/player.ts
web/src/views/public/tracks/Show.vue
web/yarn.lock

Added the ability for the user to shuffle the audio and unshuffle
Closes #98

Audio shuffle

---

web/src/components/Album.vue
web/src/store/modules/player.ts
web/src/views/public/reciters/Show.vue
web/src/views/public/tracks/Show.vue

This PR will be fixing the following bugs mentioned below
Closes #110 
Closes #114 
Closes #115

Fixing bugs

---

api/app/Console/Commands/Seed/PopularEntities.php
api/app/Database/Doctrine/EntityManager.php
api/app/Http/Controllers/Api/PopularEntitiesController.php
api/app/Providers/DoctrineServiceProvider.php
api/app/Providers/RepositoryServiceProvider.php
api/app/Repositories/Cache/CachedPopularEntitiesRepository.php
api/app/Repositories/Doctrine/DoctrinePopularEntitiesRepository.php
api/app/Repositories/Doctrine/DoctrineReciterRepository.php
api/app/Repositories/Doctrine/DoctrineTrackRepository.php
api/app/Repositories/PopularEntitiesRepository.php
api/app/Repositories/ReciterRepository.php
api/app/Repositories/TrackRepository.php
api/config/app.php
api/config/cache.php
api/config/database.php
api/config/doctrine.php
api/config/session.php
docker-compose.yml
k8s/base/deployments.yml
k8s/base/services.yml

This PR introduces Redis. We'll be using Redis for session storage along with caching. For now, we'll use Redis via K8S, but we may decide to switch to DigitalOcean's managed Redis for $15/mo for production.

Introduce Redis

---

web/src/components/LyricsViewer.vue
web/src/components/edit/EditTrackDialog.vue
web/src/components/edit/lyrics/TimestampedEditor.vue
web/src/constants/lyrics/group-type.ts
web/src/types/lyrics.ts
web/src/utils/LyricsHighlighter.ts

This PR adds support for spacers in lyrics.

Spacers (i.e. line breaks) in Lyrics

---

web/src/components/edit/lyrics/TimestampedEditor.vue

Also adds a refactored action bar for the editor.

Add JSON editor for lyrics.

---

web/src/components/edit/lyrics/TimestampedEditor.vue

In the new Lyrics Editor, these changes allow handling tracks without existing lyrics.

Lyrics Editor: Handle tracks without lyrics.

---

web/src/components/LyricsViewer.vue
web/src/layouts/LyricsPrint.vue

Made the format display correctly when printing the lyrics
Sample PDF
[Nawhas.com.pdf](https://github.com/nawhas/nawhas/files/4431919/Nawhas.com.pdf)

Fixed the print layout

---

api/Dockerfile
api/docker/entrypoint.sh
docker-compose.prod.yml
docker-compose.yml
docker/nginx/api.conf
docker/nginx/ingress.conf
k8s/base/configs/nginx.conf
k8s/base/deployments.yml
k8s/base/ingress.yml
k8s/base/kustomization.yml
k8s/base/services.yml
k8s/overlays/integration/ingress.yml
k8s/overlays/production/ingress.yml
k8s/overlays/staging/ingress.yml

I've been noticing that our application in production is crashing far too often and with no discernible cause. I'm hoping that separating the containers might lead to a more stable environment.

Separate PHP-FPM and Nginx Containers

---

web/src/views/public/HomeView.vue

Fix navigating to track page from popular tracks playing.

---

web/src/components/auth/UserMenu.vue

Fix user menu avatar alignment on mobile/tablet.

---

api/app/Database/Doctrine/Mappings/SocialAccountMapping.php
api/app/Entities/User.php
api/app/Http/Controllers/Api/AuthController.php
api/app/Http/Controllers/OAuthController.php
api/app/Http/Kernel.php
api/config/services.php
api/resources/lang/en/auth.php
api/routes/api.php
api/routes/web.php
web/src/components/auth/SocialLoginButton.vue

Builds on top of #184 to refactor / clean up some of the Socialite code.

Refactor OAuth Login Flows

---

api/app/Database/Doctrine/Mappings/AuditRecordMapping.php
api/app/Entities/Album.php
api/app/Entities/Lyrics.php
api/app/Entities/Track.php
api/app/Modules/Audit/Auditor.php
api/app/Modules/Audit/Entities/AuditRecord.php
api/app/Modules/Audit/Entities/AuditableEntity.php
api/app/Modules/Audit/EntityResolver.php
api/app/Modules/Audit/Events/AuditableEvent.php
api/app/Modules/Audit/Queries/AuditRecordQuery.php
api/app/Modules/Audit/Repositories/AuditRepository.php
api/app/Modules/Audit/Repositories/DoctrineAuditRepository.php
api/app/Modules/Authentication/Guard.php
api/app/Modules/Library/Events/AlbumModified.php
api/app/Modules/Library/Events/LyricsModified.php
api/app/Modules/Library/Events/ReciterModified.php
api/app/Modules/Library/Events/TrackModified.php
api/app/Providers/RepositoryServiceProvider.php
api/app/Queries/Query.php
api/database/migrations/doctrine/Version20200701003746.php

At this point, audit records are being saved in the database properly.

Set up persistence layer for audit records.

---

web/src/components/auth/UserMenu.vue
web/src/router/index.ts

Added the ability to guard the moderator pages with `moderatorOnly` meta tag against the route

Audit navigation guards

---

api/app/Entities/Track.php
api/app/Modules/Audit/Auditor.php
api/app/Modules/Audit/Transformers/AuditRecordTransformer.php
api/routes/api.php
web/src/layouts/ModeratorLayout.vue

Fixes #204, fixes #205, fixes #206

Audit Fixes

---

web/src/components/moderator/DiffTable.vue
web/src/components/moderator/DiffTableRow.vue

Allow toggling diff table to hide unchanged rows

---

api/app/Modules/Lyrics/Documents/Document.php
api/app/Modules/Lyrics/Documents/JsonV1/Document.php
api/app/Modules/Lyrics/Documents/PlainText/Document.php
api/tests/Unit/Modules/Lyrics/Documents/JsonV1DocumentTest.php
api/tests/Unit/Modules/Lyrics/Documents/PlainTextDocumentTest.php

Taking some changes from #211 and going straight to develop.

Add isEmpty() method to Lyrics Document.

---

api/app/Modules/Core/Events/EventSerializer.php
api/app/Modules/Core/Events/HasUserContext.php
api/app/Modules/Core/Events/UserAwareEvent.php
api/app/Modules/Library/Data/Album.php
api/app/Modules/Library/Data/Reciter.php
api/app/Modules/Library/Events/Albums/AlbumArtworkChanged.php
api/app/Modules/Library/Events/Albums/AlbumCreated.php
api/app/Modules/Library/Events/Albums/AlbumDeleted.php
api/app/Modules/Library/Events/Albums/AlbumTitleChanged.php
api/app/Modules/Library/Events/Albums/AlbumViewed.php
api/app/Modules/Library/Events/Albums/AlbumYearChanged.php
api/app/Modules/Library/Events/EntityViewed.php
api/app/Modules/Library/Events/Lyrics/LyricsChanged.php
api/app/Modules/Library/Events/Lyrics/LyricsCreated.php
api/app/Modules/Library/Events/Lyrics/LyricsDeleted.php
api/app/Modules/Library/Events/Reciters/ReciterAvatarChanged.php
api/app/Modules/Library/Events/Reciters/ReciterCreated.php
api/app/Modules/Library/Events/Reciters/ReciterDeleted.php
api/app/Modules/Library/Events/Reciters/ReciterDescriptionChanged.php
api/app/Modules/Library/Events/Reciters/ReciterNameChanged.php
api/app/Modules/Library/Events/Reciters/ReciterViewed.php
api/app/Modules/Library/Events/Tracks/TrackAudioChanged.php
api/app/Modules/Library/Events/Tracks/TrackCreated.php
api/app/Modules/Library/Events/Tracks/TrackDeleted.php
api/app/Modules/Library/Events/Tracks/TrackLyricsChanged.php
api/app/Modules/Library/Events/Tracks/TrackTitleChanged.php
api/app/Modules/Library/Events/Tracks/TrackViewed.php
api/app/Modules/Library/Events/UserAction.php
api/app/Modules/Library/Projectors/RecitersProjector.php

Helps us prepare for auditing in the future.

Add user context to events.

---

api/Dockerfile

This should speed up the API image builds by a lot.

Optimize API dockerfile.

---

nuxt/api/features.ts
nuxt/components/auth/AuthDialog.vue
nuxt/components/navigation/UserMenu.vue
nuxt/entities/features.ts
nuxt/middleware/initialize.ts
nuxt/plugins/api.ts
nuxt/store/features.ts

Nuxt: Add features API.

---

nuxt/assets/tracks/_cards.scss
nuxt/components/loaders/LyricsSkeleton.vue
nuxt/components/lyrics/LyricsCard.vue
nuxt/components/lyrics/LyricsRenderer.vue
nuxt/pages/reciters/_id/albums/_albumId/tracks/_trackId/index.vue

Nuxt: Add track view.

---

nuxt/.eslintrc.js
nuxt/components/search/AlbumResult.vue
nuxt/components/search/GlobalSearch.vue
nuxt/components/search/IndexResults.vue
nuxt/components/search/ReciterResult.vue
nuxt/components/search/TrackResult.vue

Nuxt: Add highlighting and cropping to search.

---

nuxt/assets/app.scss
nuxt/layouts/default.vue
nuxt/nuxt.config.js

Nuxt: Add page transitions.

---

nuxt/layouts/default.vue

Nuxt: Add toaster.

---

nuxt/api/tracks.ts
nuxt/pages/RecitersListPage.vue

Also fixes pagination on reciter list page to go to top of page when changing pages.
Closes #302

Nuxt: Fix Popular Tracks on Reciter Profile Page

---

api/app/Modules/Library/Http/Controllers/TracksController.php
nuxt/components/audio-player/QueueList.vue
nuxt/components/edit/EditTrackDialog.vue

This PR will close the below issues
Closes #310
Closes #312
Closes #316

Nuxt/Bug Fixes

---

nuxt/plugins/theme.client.ts
nuxt/services/theme.ts

Also cleaned up console.log statements here.
Fixes #322

Fix window.matchMedia.addEventListener for safari.

---

nuxt/components/audio-player/AudioPlayer.vue

Fixed the issue when we was trying to play a track on FireFox
Also changed the router push statements on the audio player component
Closes #321

Fixed error when playing on FireFox

---

nuxt/components/audio-player/AudioPlayer.vue
nuxt/components/edit/EditTrackDialog.vue
nuxt/layouts/error.vue
nuxt/pages/AlbumPage.vue
nuxt/pages/ReciterProfilePage.vue
nuxt/pages/TrackPage.vue
nuxt/utils/route.ts

This PR addresses a few different issues:
* Fix router push errors. (Fixes #360)
* Use Vibrant to set background images on mounted, not fetch. (Fixes #371)
* Use asyncData() hook to fetch data and handle 404 (Fixes #372)
* Better error pages (Fixes #328)

Bug Fixes for Nawhas.com v4

---

nuxt/api/library.ts

[Library V1] API methods for library

---

api/app/Modules/Library/Http/Requests/UpdateReciterRequest.php

Fixed Updating Reciter Bug

---

api/app/Http/Controllers/Controller.php
api/app/Modules/Accounts/Http/Controllers/LibraryController.php
api/app/Modules/Accounts/Http/Requests/RemoveSavedTracksRequest.php
api/app/Modules/Accounts/Http/Requests/SaveTracksRequest.php
api/app/Modules/Accounts/Http/api.php
api/app/Modules/Accounts/Projectors/SaveablesProjector.php
api/app/Modules/Authentication/Models/User.php
api/config/event-sourcing.php
api/database/migrations/data/2020_08_20_193030_create_library_saves_table.php
api/database/migrations/data/2020_08_20_193030_create_saveables_table.php
api/resources/lang/en/validation.php

This PR implements the backend of allowing a user to save tracks.
Closes #363 
Closes #364

[Library v1] Saved Tracks Backend

---

nuxt/layouts/default.vue
nuxt/middleware/initialize.ts
nuxt/pages/library/HomePage.vue
nuxt/pages/library/LibraryPage.vue
nuxt/store/auth.ts

Added local middleware to the `LibraryLandingPage` as well as `LibraryHomePage`
closes #409

[Library V1] Middleware

---

nuxt/api/library.ts
nuxt/pages/library/HomePage.vue
nuxt/store/library.ts

Displays the tracks on the library page
closes #381 
Allow user to play all saved tracks
closes #411

[Library V1] Display saved tracks on library home page

---

nuxt/store/library.ts

[Library V1] Add toaster message on saveTrack and removeTrack

---

nuxt/layouts/default.vue
nuxt/pages/HomePage.vue

[Library V1] Added saved tracks to the Home Page

---

nuxt/pages/TrackPage.vue

closes #405 
As we are already getting the tracks which belong to the album in a not paginated state, i thought it is better that we fetch the relevant data along with the initial request now that we are doing server side rendering for that

Bug 405 Fixed

---

nuxt/components/audio-player/AudioPlayer.vue

[Bugs] Fix audio player transition issue

---

nuxt/components/audio-player/AudioPlayer.vue
nuxt/pages/TrackPage.vue

https://pr-440.intg.k8s.nawhas.com
#405 
#441 
#442

Bug Integration PR

---

nuxt/components/library/LibraryHeader.vue
nuxt/components/tracks/FavoriteTrackButton.vue
nuxt/components/tracks/TrackCard.vue

Add Favorite button to Track Card

---

api/app/Modules/Audit/Models/Revision.php
api/app/Modules/Audit/Projectors/TrackRevisionsProjector.php
api/app/Modules/Audit/Snapshots/TrackSnapshot.php
api/app/Modules/Library/Events/Tracks/TrackVideoChanged.php
api/app/Modules/Library/Http/Controllers/TracksController.php
api/app/Modules/Library/Http/Requests/UpdateTrackRequest.php
api/app/Modules/Library/Http/Transformers/TrackTransformer.php
api/app/Modules/Library/Models/Track.php
api/app/Modules/Library/Projectors/TracksProjector.php
api/config/event-sourcing.php
api/database/migrations/data/2020_09_26_182901_add_video_column_to_tracks_table.php
nuxt/components/edit/EditTrackDialog.vue
nuxt/entities/track.ts
nuxt/nuxt.config.js
nuxt/package.json
nuxt/pages/TrackPage.vue
nuxt/plugins/youtube.ts
nuxt/yarn.lock

Allow associating tracks with YouTube videos. 
**TODO**
---

YouTube Videos

---

api/app/Modules/Audit/Enum/EntityType.php
api/app/Modules/Audit/Http/Transformers/RevisionTransformer.php
api/app/Modules/Audit/Projectors/TopicRevisionsProjector.php
api/app/Modules/Audit/Snapshots/AlbumSnapshot.php
api/app/Modules/Audit/Snapshots/TopicSnapshot.php
api/app/Modules/Audit/Snapshots/TrackSnapshot.php
api/app/Modules/Library/Events/Topics/TopicCreated.php
api/app/Modules/Library/Events/Topics/TopicEvent.php
api/app/Modules/Library/Http/Controllers/TopicsController.php
api/app/Modules/Library/Http/Requests/CreateTopicRequest.php
api/app/Modules/Library/Http/Transformers/TopicTransformer.php
api/app/Modules/Library/Http/api.php
api/app/Modules/Library/Models/Topic.php
api/app/Modules/Library/Projectors/TopicsProjector.php
api/app/Providers/AppServiceProvider.php
api/config/event-sourcing.php
api/database/migrations/data/2020_10_09_222749_create_topics_table.php
nuxt/components/moderator/revisions/RevisionHistoryCard.vue
nuxt/entities/revision.ts

Topics: Setup

---

nuxt/components/search/GlobalSearch.vue
nuxt/nuxt.config.js
nuxt/package.json
nuxt/yarn.lock

Disable auto-correct for search and add GTM.

---

nuxt/components/navigation/UserMenu.vue
nuxt/middleware/initialize.ts
nuxt/store/app.ts
nuxt/store/index.ts

Allows us to see what version is currently deployed in order to troubleshoot issues.

Show app version in user menu.

---

api/Dockerfile
api/app/Console/Commands/Dusk/WaitForDuskDependencies.php
api/app/Console/Commands/Search/SetUpSearch.php
api/app/Http/Controllers/Api/SearchController.php
api/app/Http/Kernel.php
api/app/Http/Middleware/AuthorizeByRole.php
api/app/Modules/Audit/Http/Transformers/RevisionTransformer.php
api/app/Modules/Audit/Models/Revision.php
api/composer.json
api/composer.lock
api/phpstan.neon
docker-compose.dev.yml
docker-compose.yml
k8s/base/deployments.yml
nuxt/@types/nawhas/index.d.ts
nuxt/Dockerfile
nuxt/components/search/IndexResults.vue
nuxt/package.json
nuxt/yarn.lock

* Allow running the project locally on Apple Silicon
* Upgrade Meilisearch to v0.25.0 and related frontend and backend code
* Fix 500 error caused by #529 using PHP Enums

Fix Moderator Dashboard & Local Dev on Apple Silicon

---

docker-compose.yml
k8s/base/deployments.yml

Breaking Change highlighted here: https://github.com/meilisearch/MeiliSearch/releases/tag/v0.24.0

Fix meilisearch volumne mount path

---

.github/actions/web-build/action.yml

Fix app version displayed in-app

---

nuxt/nuxt.config.js

https://sentry.nuxtjs.org/guide/performance

Enable tracing for Nuxt

---

nuxt/components/edit/EditDraftLyrics.vue
nuxt/layouts/error.vue
nuxt/plugins/errors.ts

Redirecting the user to an error page if the record is already locked

added status for lock/unlock

---

api/app/Modules/Library/Http/Controllers/DraftLyricsController.php
api/app/Modules/Library/Http/Requests/Drafts/Lyrics/ListDraftLyricsRequest.php
api/app/Modules/Library/Http/Transformers/DraftLyricsTransformer.php
api/app/Modules/Library/Policies/DraftLyricsPolicy.php
nuxt/api/draftLyrics.ts
nuxt/components/edit/EditDraftLyrics.vue
nuxt/components/moderator/draftLyrics/DraftLyricsCard.vue
nuxt/entities/lyrics.ts
nuxt/layouts/moderator.vue
nuxt/pages/moderator/DraftLyricsPage.vue

- Allowing the moderator to see all draft lyrics and publish them
- Fixed issue where Moderator was not able to override lock if someone else (contributor or moderator) had locked the record before
- Refactored so that when user presses the edit draft lyrics icon, it does all relevant checks before opening the dialog. Only opens the dialog if its moderator, or if the lock was successful if we have draft lyrics

Contributors v1 Moderator Integration

---

k8s/base/deployments.yml

I really don't know what this will do. But,

Try higher liveness/readiness probe timeouts

---

k8s/base/deployments.yml

https://chatgpt.com/share/6626e749-117f-41b6-8f79-c59a555699ca

Use GPT's suggestions for liveness and readiness probe settings

---

.github/workflows/staging.deploy.yml
api/Dockerfile
k8s/base/deployments.yml
k8s/helm/nawhas/templates/deployment-api-nginx.yaml
k8s/helm/nawhas/templates/deployment-api.yaml
k8s/helm/nawhas/templates/deployment-queue.yaml
k8s/overlays/production/deployments.yml
k8s/overlays/staging/deployments.yml

* Trying to use init containers to boot the application, rather than an entrypoint file.

k8s improvements

---

nuxt/components/edit/EditDraftLyrics.vue
nuxt/components/lyrics/LyricsCard.vue
nuxt/components/lyrics/LyricsRenderer.vue

Add call to action button to add a write up

---

api/app/Modules/Library/Models/DraftLyrics.php
nuxt/api/draftLyrics.ts
nuxt/components/moderator/draftLyrics/DraftLyricsCard.vue

added publish to moderator dashboard along with lyrics diff
