nawhas/nawhas

api/app/Database/Doctrine/Mappings/LyricsMapping.php
api/app/Database/Doctrine/Mappings/TrackMapping.php
api/app/Entities/Lyrics.php
api/app/Entities/Track.php
api/app/Http/Transformers/LyricsTransformer.php
api/app/Http/Transformers/TrackTransformer.php
api/app/Http/Transformers/Transformer.php
api/composer.lock
api/database/migrations/doctrine/Version20200213031919.php
api/database/seeds/TestDataSeeder.php

Closes #4
You can now visit a route like
```
https://api.nawhas.test/v1/reciters/nadeem-sarwar/albums/2019/tracks/ya-ali-ya-hussain?include=lyrics
```
And get the lyrics back:
```json
{
"id": "c6babe82-4e12-11ea-b3ef-0242ac1a0004",
"reciterId": "c6b91c3a-4e12-11ea-bd0f-0242ac1a0004",
"albumId": "c6b9cc02-4e12-11ea-9b9b-0242ac1a0004",
"title": "Ya Ali Ya Hussain",
"slug": "ya-ali-ya-hussain",
"year": "2019",
"createdAt": "2020-02-13T03:41:54+00:00",
"updatedAt": "2020-02-13T03:41:54+00:00",
"lyrics": {
"id": "c6bb25f2-4e12-11ea-8bba-0242ac1a0004",
"trackId": "c6babe82-4e12-11ea-b3ef-0242ac1a0004",
"content": "Hello World",
"createdAt": "2020-02-13T03:41:54+00:00",
"updatedAt": "2020-02-13T03:41:54+00:00"
}
}
```

Add support for read-only lyrics via API.

---

api/app/Database/Doctrine/Mappings/MediaMapping.php
api/app/Entities/Media.php
api/app/Enum/MediaProvider.php
api/app/Enum/MediaType.php
api/app/Http/Transformers/MediaTransformer.php
api/app/Providers/DoctrineServiceProvider.php
api/composer.json
api/composer.lock
api/database/migrations/doctrine/Version20200218153256.php

Response looks like this now:
```json
{
"id": "a1821f3a-51a9-11ea-a146-0242ac1a0004",
"reciterId": "a1601d40-51a9-11ea-af73-0242ac1a0004",
"albumId": "a175d5f4-51a9-11ea-a03c-0242ac1a0004",
"title": "Taqseer Te Nai Koi Syedasdi",
"slug": "taqseer-te-nai-koi-syedasdi",
"year": "2009",
"createdAt": "2020-02-17T17:19:18+00:00",
"updatedAt": "2020-02-18T01:59:13+00:00",
"media": {
"data": [
{
"id": "8eb5da3e-51f1-11ea-bb42-0242c0a85004",
"uri": "https://s3.us-east-2.amazonaws.com/zain.local.nawhas/reciters/adeem-raza-messum-zaidi/albums/2009/tracks/taqseer-te-nai-koi-syedasdi.mp3",
"type": "audio",
"provider": "file",
"createdAt": "2020-02-18T01:54:11+00:00",
"updatedAt": "2020-02-18T01:54:11+00:00"
}
]
}
}
```

Separate out provider and type for media entity using enums

---

web/src/components/audio-player/AudioPlayer.vue
web/src/store/modules/player.ts

Closes #107 
User can do the following
repeat off -> The audio will not loop
repeat all -> At the end of the queue, the player will again play the first track
repeat one -> The current track will continue to loop

[Feature] Adding repeat to audio player

---

api/app/Console/Commands/CreateUserCommand.php

This PR allows the admins to create a new user from the command line
`php artisan user:create --name={name} --email={email} --moderator`
Available options
`--name` -> this is the user's full name
`--email` -> this is the user's email address
`--moderator` -> this identifies that the user is a moderator
`--contributor` -> this identifies that the user is a contributor
`--moderator` and `--contributor` cannot be used at the same time. The script will return false
The script will ask the user for a password, if no password is supplied then a random password will be generated
Will output the details to the user and ask for confirmation if the details are correct
If the details are correct then the user will be created

Add the ability to create a new user from the command line

---

web/src/views/public/tracks/Show.vue

So as part of a previous bug fix we are checking to see if the audio has audio or not. This was picking up from the `related` attributes.
On the tracks page, we were not calling `related` so now making tracks page also pick the `related` attributes such as `lyrics: true, audio: true`
Closes #118

Fixed #118

---

api/app/Http/Kernel.php
api/routes/api.php

This is the easiest way to guard the edit routes.
Also in this PR: disable api rate limiting.

Guard edit routes

---

api/config/doctrine.php

There's no reason to set the doctrine cache driver separately.

Sync doctrine cache config with CACHE_DRIVER env variable.

---

api/app/Console/Commands/ImportDataCommand.php
api/app/Database/Doctrine/Mappings/LyricsMapping.php
api/app/Entities/Lyrics.php
api/app/Http/Controllers/Api/TracksController.php
api/app/Http/Transformers/LyricsTransformer.php
api/database/migrations/doctrine/Version20200331233330.php
api/database/migrations/doctrine/Version20200403204321.php
api/database/seeds/TestDataSeeder.php

This PR adds a version number to lyrics, which will allow the frontend to handle various types of lyrics content without the need of a database level migration.
A version number in the lyrics object in the track response will provide necessary information to the frontend to handle displaying different types of lyrics content.
<details>
<summary>Example Response</summary>
```json
{
"id": "8f08f7d0-5ff4-11ea-818c-327c6b7fa86c",
"reciterId": "4105f6a8-5407-11ea-922c-6eb465563d0f",
"albumId": "9bb82a98-5ff2-11ea-ad34-327c6b7fa86c",
"title": "Roti Hai Sakina",
"slug": "roti-hai-sakina",
"year": "2019",
"createdAt": "2020-03-06T21:50:56+00:00",
"updatedAt": "2020-03-06T22:00:33+00:00",
"lyrics": {
"id": "8f090716-5ff4-11ea-8037-327c6b7fa86c",
"trackId": "8f08f7d0-5ff4-11ea-818c-327c6b7fa86c", …
```

Add version number to lyrics.

---

web/src/components/LyricsViewer.vue
web/src/components/audio-player/AudioPlayer.vue
web/src/components/edit/EditTrackDialog.vue
web/src/components/edit/lyrics/TimestampedEditor.vue
web/src/types/lyrics.ts
web/src/views/public/tracks/TrackView.vue

Lyrics Refactor

---

web/src/views/public/tracks/Show.vue

In preparation for the Timestamped Lyrics release, we want to prevent displaying the JSON formatted lyrics in the app until the app has updated to support the new format.
This is especially necessary because, while the frontend is cached in the browser, the API response will not be. 
If the user has a cached version of the app and we deploy the timestamped lyrics feature, this will be shown:
Instead, with this change, the user will now see 
**We need to get this PR out to production ASAP so that there's less chance a user will be on a far too outdated version of the app.**

Don't show lyrics if not plain text

---

web/src/App.vue
web/src/components/auth/UserMenu.vue
web/src/layouts/Public.vue
web/src/styles/variables.scss

Almost every single other website uses a max width of around 1100-1200px for their application. This ensures that the app looks decent even when some people ( 😉) choose to use the website in full screen on a 4k screen.
Here are some comparison screenshots.
---
A more useful comparison might be on a normal, yet still really wide, resolution:
---

Use a more sane max width for the application.

---

web/src/components/audio-player/AudioPlayer.vue

Fix audio player queue styling on desktop.

---

dev
docker-compose.yml
docker/postgres/scripts/clean_database
docker/postgres/scripts/sync_database

`./dev db:sync` will synchronize your database with the data from the staging db without destroying your **users**.
`./dev db:refresh` will set everything back up exactly as staging has it (without certain tables, like `users` or `social_accounts`
```bash
$ dev db:sync
Recreating nawhas_db ... done
+ docker-compose exec api php artisan doctrine:migrations:migrate
Nothing to migrate.
+ run db sync_database
+ set -x
+ docker-compose exec db sync_database
Dumping database from staging to /opt/dump.sql.
Restoring database from /opt/dump.sql.
Done!
```

Add db:sync and db:refresh commands to dev tool.

---

api/app/Entities/Track.php
api/app/Http/Controllers/Api/TracksController.php
api/app/Modules/Library/Events/LyricsDeleted.php
api/app/Modules/Lyrics/Documents/Document.php
api/app/Modules/Lyrics/Documents/JsonV1/Document.php
api/app/Modules/Lyrics/Documents/PlainText/Document.php
api/tests/Unit/Modules/Lyrics/Documents/JsonV1DocumentTest.php
api/tests/Unit/Modules/Lyrics/Documents/PlainTextDocumentTest.php

When a track is updated with lyrics without any useful content, we will now smartly handle it.
If the content is empty and there's no old version of lyrics associated to the track, we'll ignore the change
entirely.
If the content is not empty and there is no old version of lyrics, this counts as a "create" operation.
If the content is empty and there is an old version of lyrics, this counts as a "delete" operation.
Tests included.
Fixes #205, fixes #206 
Example:

Better handle lyrics modifications.

---

.github/workflows/integration.deploy.yml

We use the branch name of a pull request to determine whether we want to trigger an integration environment deploy. We were accidentally using the wrong variable for this.
- PR `develop` ◀️ `some-integration`: ❌ No integration build triggered.
- PR `some-integration` ◀️ `feature/something`: ✅ Integration build triggered incorrectly.
- PR `develop` ◀️ `some-integration`:  ✅ Integration build triggered
- PR `some-integration` ◀️ `feature/something`:  ❌ No integration build triggered.

Use HEAD ref instead of BASE ref for integration build triggers.

---

api/app/Console/Commands/BootApplication.php
api/app/Console/Commands/MigrateAllDatabases.php
api/app/Events/StoredEvent.php
api/config/database.php
api/config/doctrine.php
api/config/event-sourcing.php
api/database/migrations/events/2020_07_21_011640_create_snapshots_table.php
api/database/migrations/events/2020_07_21_011640_create_stored_events_table.php
docker-compose.yml

Multiple Databases!!
`events` database stores our events. This will be shared across all production app instances.
`data` database will store our projected, read-only models by processing events.
`pgsql` database is the (now) "legacy" Doctrine database.
Run the following command to run database migrations for everything!
```
php artisan migrate:all
```

Database Setup for Event Sourcing

---

api/config/database.php

This will tell Laravel to use the `data` database by default for all database related queries, like unique validation rules in Requests.

Fix request validations by specifying correct default database connection.

---

api/config/doctrine.php

Stop using Doctrine's presence verifier.
Note that this will break all old FormRequest classes that use the `unique` or `exists` rule with the Doctrine syntax (`exists:App\Entities\User...`)

Use Laravel's presence verifier.

---

api/app/Console/Commands/Meilisearch/SetupScout.php
api/composer.json
api/composer.lock
api/config/meilisearch.php
docker/nginx/ingress.conf

Adds https://search.nawhas.test as a new domain name. You'll need to generate a new certificate for this:
```
docker/nginx/certs
├── search.nawhas.test.crt
└── search.nawhas.test.key
```
I used the following command:
```
mkcert \
--cert-file search.nawhas.test.crt \
--key-file search.nawhas.test.key \
search.nawhas.test localhost 127.0.0.1 10.0.0.60 ::1
```
Afterwards, you'll need to add `127.0.0.1 search.nawhas.test` to your hosts file as well.

Setup Meilisearch for Local Dev

---

api/app/Console/Commands/Meilisearch/SetupMeilisearch.php
api/app/Http/Controllers/Api/SearchController.php
api/app/Providers/AppServiceProvider.php
api/config/meilisearch.php
api/routes/api.php
nuxt/@types/nawhas/index.d.ts
nuxt/components/search/GlobalSearch.vue
nuxt/nuxt.config.js
nuxt/plugins/search.ts

This PR sets up index settings in the API backend, and exposes a new API route (`GET v1/search/key`) to fetch the public key used for Meilisearch. Nuxt then consumes this endpoint during the server side render process and injects Meilisearch into the context as `$search`.

Nuxt: Search Configuration

---

nuxt/nuxt.config.js
nuxt/pages/AboutPage.vue
nuxt/pages/AlbumPage.vue
nuxt/pages/ReciterProfilePage.vue
nuxt/pages/RecitersListPage.vue
nuxt/pages/TrackPage.vue
nuxt/store/features.ts
nuxt/utils/meta.ts

This PR adds open graph meta tags using a helper method to each of the pages we care about. The content below applies to both the `<title>` and `<meta name="description">` tags,  as well as `og:title` and `og:description`.
> **Reciters | Nawhas.com**
> Browse, read, and listen to over 6000 nawhas by more than 100 different reciters, including world-famous nawhakhwans like Nadeem Sarwar, Irfan Haider, Tejani Brothers, Hassan Sadiq, Mir Hasan Mir, and more!
> **Tejani Brothers | Nawhas.com**
> Explore Tejani Brothers&#x27;s collection of nawhas from 15 albums.
> **Shia (2019) - Album by Tejani Brothers | Nawhas.com**
> Released in 2019, Shia is an album by Tejani Brothers with 9 nawhas, including Akbar Tere Jigar Se, Ark of Salvation (English), Day of Ashura (English), and more.
> **Shame …

Nuxt: Add better metadata to all pages.

---

nuxt/pages/AlbumPage.vue
nuxt/pages/ReciterProfilePage.vue
nuxt/pages/TrackPage.vue
nuxt/utils/meta.ts

This change adds the avatar/artwork on the following pages
`ReciterProfilePage` -> adds the Reciter Avatar if it has one, otherwise displays the default avatar
`AlbumPage` as well as `TrackPage` -> adds the album artwork if it has one, otherwise displays the default artwork
Closes #305

Added image to Reciter page, Album page and Track page

---

nuxt/entities/theme.ts
nuxt/layouts/default.vue
nuxt/nuxt.config.js
nuxt/package.json
nuxt/plugins/theme.client.ts
nuxt/services/theme.ts
nuxt/store/preferences.ts
nuxt/vuetify.options.ts

By moving the actual step of applying the theme to Vuetify to the layout `mounted()` hook, we can be sure that the theme is applied properly and uniformly across the board.

Nuxt: Fix dark mode first render.

---

nuxt/api/auth.ts
nuxt/package.json
nuxt/plugins/axios.ts
nuxt/yarn.lock

Auto-refresh CSRF if a failure is 419 CSRF Token Mismatch

Refresh CSRF cookie when request fails with 419.

---

api/app/Http/Kernel.php
api/app/Infrastructure/Cache/Middleware/CacheResponse.php
api/app/Infrastructure/Cache/Middleware/ClearResponseCache.php
api/app/Modules/Accounts/Http/CacheTags.php
api/app/Modules/Accounts/Http/api.php
api/app/Modules/Authentication/Http/CacheTags.php
api/app/Modules/Authentication/Http/api.php
api/app/Modules/Library/Http/CacheTags.php
api/app/Modules/Library/Http/api.php

Using cache tags, I can make sure to clear the right pieces of cached responses so that the saved tracks responses are cached, but only those are invalidated when saving a new track.

Fix cache for library saved tracks.

---

api/app/Modules/Authentication/Models/User.php
api/app/Modules/Library/Models/Track.php
api/app/Modules/Library/Models/Visits/TrackStatistic.php
api/app/Modules/Library/Projectors/TrackStatisticsProjector.php
api/database/migrations/data/2020_09_03_041449_create_track_statistics_table.php

I expect this to take the popular tracks endpoint down from `~14s` in production to `~0.1s`.

Add projector for incrementing track statistics to fix super slow query.

---

nuxt/components/moderator/revisions/DiffTable.vue
nuxt/layouts/moderator.vue
nuxt/pages/moderator/RevisionsPage.vue

* Closes #445: Add padding to moderator layout when audio player is playing.
* Closes #448: Fix pagination UX on revisions page
* Closes #446: Use fixed table layout to prevent one column from taking up all space.

Moderator Bug Fixes

---

api/config/session.php

A user will not be logged out unless they have been inactive for 90 days.
This is not a security concern because, well, there's not much in the way
of sensitive data here. Convenience is more important.
Closes #483.

Increase session lifetime to 90 days. Currently at 2 hours.

---

docker-compose.yml
k8s/base/deployments.yml
k8s/base/volumes.yml

Use v0.25.2 instead of v0.25.0 to see if that helps solve the k8s deploy issue.

Use newer image for Meilisearch

---

api/Dockerfile
docker-compose.dev.yml

Uses the latest PHP 8.1 docker images built using  https://github.com/szainmehdi/dockerfiles/commit/46c0b45166a31e2015ade31e96d1f0624d1328e9 and https://github.com/szainmehdi/dockerfiles/commit/565ea2d1fb0d0f07048653b38ee3e74d906a472e
```
/var/www/api # php -v
PHP 8.1.21 (cli) (built: Jul 10 2023 23:14:30) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.21, Copyright (c) Zend Technologies
with Zend OPcache v8.1.21, Copyright (c), by Zend Technologies
with Xdebug v3.2.2, Copyright (c) 2002-2023, by Derick Rethans
```

Update to latest PHP 8.1 image

---

.github/workflows/integration.deploy.yml

Previously, multiple PRs updated around the same time would cause other PR builds to be canceled. This should prevent that.

Fix CI concurrency for integration / PR builds

---

api/composer.json
api/composer.lock
api/config/sentry.php

https://docs.sentry.io/platforms/php/guides/laravel/performance/
Upgrades `sentry/sentry-laravel` from `2.14.2` to [`3.7.3`](https://github.com/getsentry/sentry-laravel/releases/tag/3.7.3)

Enable Sentry tracing and upgrade Sentry

---

nuxt/nuxt.config.js

In production:
```
➜  ~ kube logs -f web-58549658cc-5b5jn
yarn run v1.22.19
$ nuxt-ts start
ℹ Sentry reporting is disabled (no DSN has been provided)
ℹ Listening on: http://10.244.0.76:3000/
```

Enable Sentry for frontend using correct sentry DSN env variable

---

dev

Docker appears to have changed default behavior, and `docker-compose.override.yml` is no longer respected automatically.
We should definitely upgrade and rework our docker-compose setup eventually but this gets us going again for now.

Make sure to use docker-compose.override.yml

---

docker/nginx/setup.bat

This script is the equivalent to the setup.sh file in the docker/nginx folder but for Windows machines
I have tested this on my local machine and working as expected
It is adding to hosts file, creating certificate as well as storing in the windows certificate store

Added a new bat file to setup certs for windows users

---

api/app/Modules/Audit/Http/Transformers/RevisionTransformer.php
api/app/Modules/Audit/Models/Revision.php
api/app/Modules/Authentication/Models/PasswordResetToken.php
api/app/Modules/Library/Models/Visit.php

This fixes and closes issue #607 
As we are already using the $dates property on the model, there is no need to convert this to DateTime hence removed the conversion
I have tested this on my local and the Audit now appears with the correct info

Fixed issue with RevisionTransformer createdAt

---

k8s/base/deployments.yml

As per meilisearch documentation for V1.3.2 (which is the version we are currently using)
https://github.com/meilisearch/documentation/blob/v1.3/learn/getting_started/installation.mdx
The data should get mounted to `/meili_data` however we are currently mapping to folder `/home/meili/data.ms`
Due to this, whenever the container restarted, we lost our data
This should now fix this
We will have to delete the volume manually in case it contains invalid data, and then reindex the search post deployment

Fixed search volume data mapping

---

nuxt/nuxt.config.js

I've noticed that staging.nawhas.com shows up on Google search results. This should prevent Google from indexing non-production domains going forward.

Don't index non-production versions of the app

---

api/app/Http/Controllers/TransformsResponses.php
api/app/Modules/Core/Models/EagerLoadsRelations.php
api/app/Modules/Library/Http/Controllers/TracksController.php
api/app/Modules/Library/Models/Album.php
api/app/Modules/Library/Models/Track.php
api/tests/Unit/Modules/Core/Models/EagerLoadsRelationsTest.php

To help deal with the N+1 error notifications and optimize performance, I added a trait that helps eager load relations for models before sending it through the transformer. This should hopefully help a lot.

Add eager loading of includes to Track
